# Generated by Django 5.2.5 on 2025-08-19 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.CreateModel(
            name='Sympathy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mutual', models.BooleanField(default=False, verbose_name='Взаимная симпатия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Симпатия',
                'verbose_name_plural': 'Симпатии',
            },
        ),
        migrations.RemoveConstraint(
            model_name='photoreaction',
            name='unique_player_man_photo_reaction',
        ),
        migrations.RemoveConstraint(
            model_name='photoreaction',
            name='unique_player_woman_photo_reaction',
        ),
        migrations.AddField(
            model_name='player',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddConstraint(
            model_name='photoreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('man_photo__isnull', False)), fields=('player', 'man_photo'), name='unique_player_man_photo_reaction'),
        ),
        migrations.AddConstraint(
            model_name='photoreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('woman_photo__isnull', False)), fields=('player', 'woman_photo'), name='unique_player_woman_photo_reaction'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core_rndvu.player', verbose_name='Кто добавил в избранное'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core_rndvu.player', verbose_name='Кого добавили в избранное'),
        ),
        migrations.AddField(
            model_name='sympathy',
            name='from_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sympathies_out', to='core_rndvu.player', verbose_name='От кого'),
        ),
        migrations.AddField(
            model_name='sympathy',
            name='to_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sympathies_in', to='core_rndvu.player', verbose_name='Кому'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['owner', 'created_at'], name='core_rndvu__owner_i_7f99fc_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['target', 'created_at'], name='core_rndvu__target__f0bc4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('owner', 'target'), name='unique_favorite_owner_target'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.CheckConstraint(condition=models.Q(('owner', models.F('target')), _negated=True), name='favorite_owner_not_target'),
        ),
        migrations.AddIndex(
            model_name='sympathy',
            index=models.Index(fields=['from_player', 'created_at'], name='core_rndvu__from_pl_a5fd54_idx'),
        ),
        migrations.AddIndex(
            model_name='sympathy',
            index=models.Index(fields=['to_player', 'created_at'], name='core_rndvu__to_play_06888d_idx'),
        ),
        migrations.AddIndex(
            model_name='sympathy',
            index=models.Index(fields=['is_mutual'], name='core_rndvu__is_mutu_64d770_idx'),
        ),
        migrations.AddConstraint(
            model_name='sympathy',
            constraint=models.UniqueConstraint(fields=('from_player', 'to_player'), name='unique_sympathy_from_to'),
        ),
        migrations.AddConstraint(
            model_name='sympathy',
            constraint=models.CheckConstraint(condition=models.Q(('from_player', models.F('to_player')), _negated=True), name='sympathy_from_not_to'),
        ),
    ]
