# Generated by Django 5.2.5 on 2025-08-19 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0002_favorite_sympathy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilewoman',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='woman_profile', to='core_rndvu.player', verbose_name='Владелец анкеты'),
        ),
    ]
