# Generated by Django 5.2.5 on 2025-08-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0003_alter_profilewoman_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='manphoto',
            name='main_photo',
            field=models.BooleanField(default=False, verbose_name='Главное фото анкеты'),
        ),
        migrations.AddField(
            model_name='womanphoto',
            name='main_photo',
            field=models.BooleanField(default=False, verbose_name='Главное фото анкеты'),
        ),
        migrations.AlterField(
            model_name='manphoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки фото'),
        ),
        migrations.AlterField(
            model_name='womanphoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки фото'),
        ),
    ]
