# Generated by Django 5.2.5 on 2025-08-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0005_product_player_count_days_paid_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dislikes_count',
            field=models.IntegerField(default=0, verbose_name='Количество дизлайков профиля'),
        ),
        migrations.AddField(
            model_name='player',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Количество лайков профиля'),
        ),
    ]
