# Generated by Django 5.2.5 on 2025-08-31 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0006_player_dislikes_count_player_likes_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReactionDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_dislikes', to='core_rndvu.player')),
                ('to_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_dislikes', to='core_rndvu.player')),
            ],
            options={
                'verbose_name': 'Дизлайк пользователя',
                'verbose_name_plural': 'Дизлайки пользователей',
                'unique_together': {('from_player', 'to_player')},
            },
        ),
    ]
