# Generated by Django 5.2.5 on 2025-09-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0007_userreactiondislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID города из GeoNames'),
        ),
        migrations.AlterField(
            model_name='player',
            name='city',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID города из GeoNames'),
        ),
    ]
