# Generated by Django 5.2.5 on 2025-10-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0008_alter_event_city_alter_player_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='alpha2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код страны из GeoNames'),
        ),
        migrations.AddField(
            model_name='player',
            name='alpha2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код страны из GeoNames'),
        ),
    ]
