# Generated by Django 5.2.5 on 2025-10-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0009_event_alpha2_player_alpha2'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='link_tg',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AddField(
            model_name='player',
            name='verification',
            field=models.BooleanField(default=False, verbose_name='Подтверждение профиля'),
        ),
    ]
