# Generated by Django 5.2.5 on 2025-10-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0010_player_link_tg_player_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'usd'), ('USDT', 'usdt'), ('EU', 'eu'), ('RU', 'ru')], max_length=60, null=True, verbose_name='Валюта награды за ивент'),
        ),
    ]
