# Generated by Django 5.2.5 on 2025-10-20 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0011_event_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
