# Generated by Django 5.2.5 on 2025-10-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0012_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.IntegerField(blank=True, choices=[(0, 'Время обсудим в диалоге'), (1, '1 час'), (2, '2 часа'), (3, '3 часа'), (4, '4 часа'), (5, '5+ часов'), (24, '24 часа')], null=True, verbose_name='Длительность ивента'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, choices=[('restaurant', 'Ресторан'), ('cafe', 'Кофейня'), ('hotel', 'Отель'), ('apartments', 'Апартаменты'), ('restaurant_and_apartments', 'Ресторан и апартаменты'), ('yacht', 'Яхта'), ('villa', 'Вилла'), ('bath_complex', 'Банный комплекс'), ('private_house', 'Частный дом'), ('country_complex', 'Загородный комплекс'), ('private_sector', 'Частный сектор'), ('club', 'Клуб'), ('club_and_hotel', 'Клуб и отель'), ('travel_together', 'Совместная поездка'), ('any_place_you_wish', 'Любое место по вашему желанию'), ('bachelor_party', 'Мальчишник'), ('bachelorette_party', 'Девичник'), ('to_pair_with_us', 'К нам в пару'), ('has_not_been_selected_yet', 'Место пока не выбрано')], max_length=50, null=True, verbose_name='Место ивента'),
        ),
    ]
