# Generated by Django 5.2.5 on 2025-10-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0013_alter_event_duration_alter_event_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileman',
            name='about',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='О себе'),
        ),
    ]
