# Generated by Django 5.2.5 on 2025-11-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0014_alter_profileman_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.PositiveBigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина блокировки')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата блокировки')),
            ],
            options={
                'verbose_name': 'Заблокированный пользователь',
                'verbose_name_plural': 'Черный список',
                'ordering': ['-blocked_at'],
                'indexes': [models.Index(fields=['tg_id'], name='core_rndvu__tg_id_f99afe_idx')],
            },
        ),
    ]
