# Generated by Django 5.2.5 on 2025-11-04 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0015_blacklistuser'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blacklistuser',
            name='core_rndvu__tg_id_f99afe_idx',
        ),
        migrations.RemoveField(
            model_name='blacklistuser',
            name='tg_id',
        ),
        migrations.AddField(
            model_name='blacklistuser',
            name='player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entry', to='core_rndvu.player', verbose_name='Пользователь'),
        ),
    ]
