# Generated by Django 5.2.5 on 2025-11-04 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0016_remove_blacklistuser_core_rndvu__tg_id_f99afe_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistuser',
            options={'ordering': ['-blocked_at'], 'verbose_name': 'Заблокированный пользователь', 'verbose_name_plural': 'Заблокированные пользователи'},
        ),
    ]
