# Generated by Django 5.2.5 on 2025-11-04 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0017_alter_blacklistuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата пропуска')),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed_users', to='core_rndvu.player', verbose_name='Кто пропустил')),
                ('to_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed_by_users', to='core_rndvu.player', verbose_name='Кого пропустили')),
            ],
            options={
                'verbose_name': 'Пропущенный пользователь',
                'verbose_name_plural': 'Пропущенные пользователи',
                'indexes': [models.Index(fields=['from_player', 'created_at'], name='core_rndvu__from_pl_cdbc11_idx'), models.Index(fields=['to_player'], name='core_rndvu__to_play_5b5e32_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_player', 'to_player'), name='unique_passed_from_to'), models.CheckConstraint(condition=models.Q(('from_player', models.F('to_player')), _negated=True), name='passed_from_not_to')],
            },
        ),
    ]
