# Generated by Django 5.2.5 on 2025-11-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0018_passeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'usd'), ('USDT', 'usdt'), ('EUR', 'eur'), ('RUB', 'rub')], max_length=60, null=True, verbose_name='Валюта награды за ивент'),
        ),
    ]
