# Generated by Django 5.2.5 on 2025-11-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0019_alter_event_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='candidate',
            field=models.CharField(blank=True, choices=[('Man', 'Парня'), ('Women', 'Девушку')], null=True, verbose_name='Кого ищут'),
        ),
    ]
