# Generated by Django 5.2.5 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0020_event_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='show_in_game',
            field=models.BooleanField(default=True, verbose_name='Показ в игре да/нет'),
        ),
    ]

