# Generated by Django 5.2.5 on 2025-11-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0023_alter_product_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gift',
            field=models.CharField(blank=True, choices=[("I've got a gift", 'С меня подарок'), ('I want a gift', 'Хочу подарок')], max_length=50, null=True, verbose_name='Кто дарит подарок'),
        ),
    ]
