# Generated by Django 5.2.5 on 2025-12-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0024_event_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='alpha2',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Код страны (ISO Alpha-2/Alpha-3)'),
        ),
    ]
