# Generated by Django 5.2.5 on 2025-12-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0025_alter_event_alpha2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='alpha2',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Код страны (ISO Alpha-2/Alpha-3)'),
        ),
    ]
