# Generated by Django 5.2.5 on 2025-12-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0026_alter_player_alpha2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('week', '1 неделя'), ('week_2', '2 неделя'), ('monthly', '1 месяц'), ('yearly', '1 год')], max_length=20, null=True, verbose_name='Тип подписки'),
        ),
    ]
