# Generated by Codex on 2026-01-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_rndvu', '0027_alter_product_subscription_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('week', '1 неделя'), ('week_2', '2 неделя'), ('monthly', '1 месяц'), ('yearly', '1 год')], max_length=20, verbose_name='Тип подписки')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Количество дней')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_grants', to=settings.AUTH_USER_MODEL, verbose_name='Кто выдал')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_grants', to='core_rndvu.player', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выдача подписки',
                'verbose_name_plural': 'Выдачи подписок',
            },
        ),
    ]
